# Generated by Django 4.1.9 on 2023-06-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='status',
            field=models.CharField(choices=[('Təklif', 'Təklif'), ('Şikayət', 'Şikayət')], max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Qadın', 'Qadın'), ('Kişi', 'Kişi')], max_length=30, verbose_name='gender'),
        ),
    ]
