# Generated by Django 4.1.9 on 2023-07-15 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_contact_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='status',
            field=models.CharField(choices=[('Şikayət', 'Şikayət'), ('Təklif', 'Təklif')], max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Qadın', 'Qadın'), ('Kişi', 'Kişi')], max_length=30, verbose_name='gender'),
        ),
    ]
