# Generated by Django 4.1.9 on 2023-06-10 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_category_az_product_category_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category_az',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category_ru',
        ),
    ]
