# Generated by Django 4.1.9 on 2023-06-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('online', 'online'), ('cash', 'cash'), ('cart', 'cart')], max_length=50),
        ),
    ]
