# Generated by Django 4.1.9 on 2023-06-10 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('online', 'online'), ('cash', 'cash'), ('cart', 'cart')], max_length=50),
        ),
    ]
