# Generated by Django 3.2.20 on 2023-07-14 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_alter_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('online', 'online'), ('cash', 'cash'), ('cart', 'cart')], max_length=50),
        ),
    ]
